# Generated by Django 5.2.6 on 2025-09-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hockey Game', max_length=100)),
                ('players_in_field', models.IntegerField(default=5)),
                ('total_players', models.IntegerField(default=8)),
                ('game_length', models.IntegerField(default=50, help_text='Game length in minutes')),
                ('sections', models.IntegerField(default=2, help_text='Number of game sections (halves)')),
                ('substitution_length', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], default='long', max_length=5)),
                ('paired_subbing', models.BooleanField(default=True)),
                ('player_names', models.TextField(blank=True, help_text='Comma or space separated player names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('time_blocks', models.JSONField(default=list)),
                ('player_assignments', models.JSONField(default=dict)),
                ('optimization_score', models.FloatField(blank=True, null=True)),
                ('iterations_run', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hockeysub.game')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('game', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('section', models.IntegerField(help_text='Which game section this block belongs to')),
                ('active_players', models.JSONField(default=list)),
                ('bench_players', models.JSONField(default=list)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hockeysub.schedule')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position_index', models.IntegerField()),
                ('total_playing_time', models.FloatField(default=0)),
                ('total_bench_time', models.FloatField(default=0)),
                ('substitution_count', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='hockeysub.schedule')),
            ],
            options={
                'ordering': ['position_index'],
                'unique_together': {('schedule', 'position_index')},
            },
        ),
    ]
