# Generated by Django 5.2.6 on 2025-09-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeysub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='custom_block_duration',
            field=models.FloatField(blank=True, help_text='Custom block duration in minutes (e.g., 3.5 for 3:30). If not set, automatic block sizing is used.', null=True),
        ),
    ]
