# Generated by Django 6.0.3 on 2026-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hockeysub", "0002_game_custom_block_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="substitution_mode",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (multiple subs per section)"),
                    ("zen", "Zen (one substitution per quarter)"),
                ],
                default="standard",
                max_length=10,
            ),
        ),
    ]
